version: "3.4"

services:
  filegateway:
    build:
      context: .
      dockerfile: docker/local/filegateway.Dockerfile
    ports:
      - "8080:8080"
    environment:
      FG_NUMBER_OF_CHUNKS: 3
      FG_STORAGE_SERVERS: "filestore1:9000;filestore2:9001;filestore3:9002"
    depends_on:
      - filestore1
      - filestore2
      - filestore3

  filestore1:
    build:
      context: .
      dockerfile: docker/local/filestore.Dockerfile
    ports:
      - "9000:9000"
    environment:
      FS_APP_NAME: filestore1
      FS_ID: 0
      FS_GRPC_PORT: 9000

  filestore2:
    build:
      context: .
      dockerfile: docker/local/filestore.Dockerfile
    ports:
      - "9001:9001"
    environment:
      FS_APP_NAME: filestore2
      FS_ID: 1
      FS_GRPC_PORT: 9001

  filestore3:
    build:
      context: .
      dockerfile: docker/local/filestore.Dockerfile
    ports:
      - "9002:9002"
    environment:
      FS_APP_NAME: filestore3
      FS_ID: 2
      FS_GRPC_PORT: 9002